import '../styles/globals.css'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import { ApolloClientProvider } from '@/providers/ApolloClientProvider'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale} >
      <body className={geistSans.variable} >
        <ApolloClientProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ApolloClientProvider>
      </body>
    </html>
  )
}
